export const schema = {
  title: 'Application For Software engineer position',
  showProgressBar: 'top',
  progressBarType: 'buttons',
  pages: [
    {
      name: 'personalInformation',
      navigationTitle: 'Personal information',
      navigationDescription: 'Tell us about you',
      startWithNewLine: false,
      showQuestionNumbers: 'off',
      elements: [
        {
          type: 'text',
          name: 'fullname',
          title: 'Full name',
          isRequired: true,
        },
        {
          type: 'text',
          name: 'address',
          title: 'Address',
          isRequired: true,
        },
        {
          type: 'text',
          name: 'country',
          title: 'Country',
          isRequired: true,
        },
        {
          type: 'text',
          name: 'phone',
          title: 'Telephone number',
          inputType: 'tel',
          isRequired: true,
          validators: [
            {
              type: 'regex',
              regex: '\\+[0-9]{1} \\([0-9]{3}\\) [0-9]{3}-[0-9]{2}-[0-9]{2}',
              text: 'Phone number must be in the following format: +0 (000) 000-00-00',
            },
          ],
        },
        {
          type: 'text',
          name: 'email',
          title: 'Email',
          inputType: 'email',
          isRequired: true,
        },
      ],
    },
    {
      name: 'educationTraining',
      navigationTitle: 'Education and training',
      navigationDescription: 'Tell us about your education',
      elements: [
        {
          type: 'paneldynamic',
          name: 'educations',
          title: 'Educations',
          keyName: 'diploma',
          showQuestionNumbers: 'off',
          templateTitle: 'Education #{panelIndex}',
          minPanelCount: 1,
          maxPanelCount: 3,
          panelAddText: 'Add another education',
          panelRemoveText: 'Remove education',
          templateElements: [
            {
              type: 'dropdown',
              name: 'diploma',
              title: 'Diploma',
              isRequired: true,
              showNoneItem: true,
              showOtherItem: true,
              choices: [
                'High school Degree',
                'Bachelor Degree',
                'Master Degree',
                'Doctoral Degree',
              ],
            },
            {
              type: 'text',
              name: 'school1',
              title: 'School or University',
              isRequired: true,
            },
            {
              type: 'text',
              name: 'graduationYear',
              title: 'Graduation year',
              inputType: 'date',
              isRequired: true,
            },
            {
              type: 'comment',
              name: 'description',
              title: 'Description of what you have studied',
            },
          ],
        },
      ],
    },
    {
      name: 'experience',
      navigationTitle: 'Experience',
      navigationDescription: 'Tell us more about your experience',
      elements: [
        {
          type: 'paneldynamic',
          name: 'experiences',
          title: 'Experiences',
          keyName: 'position',
          showQuestionNumbers: 'off',
          templateTitle: 'Education #{panelIndex}',
          minPanelCount: 1,
          maxPanelCount: 3,
          panelAddText: 'Add another experience',
          panelRemoveText: 'Remove experience',
          templateElements: [
            {
              type: 'text',
              name: 'position',
              title: 'Position',
              isRequired: true,
            },
            {
              type: 'text',
              name: 'company',
              title: 'Company',
              isRequired: true,
            },
            {
              type: 'text',
              name: 'startDate',
              title: 'Start date',
              inputType: 'date',
              isRequired: true,
            },
            {
              type: 'text',
              name: 'endDate',
              title: 'End date',
              inputType: 'date',
              isRequired: true,
              visibleIf: '{panel.untilNow}=false',
            },
            {
              type: 'boolean',
              name: 'untilNow',
              title: 'Until now',
              isRequired: true,
              defaultValue: false,
            },
            {
              type: 'comment',
              name: 'description',
              title: 'Description of what you have worked on',
            },
          ],
        },
      ],
    },
    {
      name: 'resumeCoverLetter',
      navigationTitle: 'Resume and cover letter',
      navigationDescription: 'Tell us why you are suitable for the position',
      elements: [
        {
          type: 'file',
          name: 'resume',
          title: 'Please upload your resume',
          showPreview: true,
          maxSize: 102400,
          isRequired: true,
        },
        {
          type: 'comment',
          name: 'coverLetter',
          title: 'why you are suitable for the position ?',
          isRequired: true,
        },
      ],
    },
  ],
};
